Fixing
$:~/Repositories/ircd.js$ node bin/ircd.js

/home/niklas/Repositories/ircd.js/lib/protocol.js:78
  invalidChannel: /[
                  ^

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
SyntaxError: Invalid regular expression: missing /
    at Module._compile (module.js:368:25)
    at Object..js (module.js:379:10)
    at Module.load (module.js:305:31)
    at Function._load (module.js:271:10)
    at require (module.js:317:19)
    at Object.<anonymous> (/home/niklas/Repositories/ircd.js/lib/server.js:25:11)
    at Module._compile (module.js:373:26)
    at Object..js (module.js:379:10)
    at Module.load (module.js:305:31)
    at Function._load (module.js:271:10)

The protocol.js file seamed to contain invalid binary characters.